In [1]:
import pandas as pd
import numpy as np

In [38]:
#df = pd.read_csv('/home/rmohring/code/rmm/advent-rmm-2024/source/day02/2_test.dat', sep="\s+", header=None)
#fh = open('/home/rmohring/code/rmm/advent-rmm-2024/source/day02/2_test.dat')
fh = open('/home/rmohring/code/rmm/advent-rmm-2024/source/day02/2-1.dat')

In [39]:
data = []
for line in fh.readlines():
    vals = line.strip("\n").split(" ")
    x2 = [int(x) for x in vals]
    data.append(np.array(x2))

In [40]:
data

[array([20, 21, 24, 25, 27, 29, 27]),
 array([60, 61, 62, 64, 64]),
 array([15, 18, 21, 22, 25, 26, 30]),
 array([ 5,  8, 11, 14, 16, 19, 20, 26]),
 array([20, 22, 20, 23, 24]),
 array([89, 91, 92, 95, 98, 95, 96, 95]),
 array([ 3,  5,  7, 10, 11, 14, 13, 13]),
 array([82, 85, 83, 84, 86, 90]),
 array([82, 83, 84, 81, 86]),
 array([27, 28, 28, 30, 33]),
 array([ 2,  4,  4,  6,  9, 10, 13, 11]),
 array([64, 65, 65, 68, 69, 72, 72]),
 array([60, 63, 63, 64, 65, 67, 71]),
 array([14, 17, 17, 20, 21, 27]),
 array([16, 19, 21, 25, 26]),
 array([57, 59, 63, 65, 62]),
 array([86, 89, 91, 95, 95]),
 array([ 2,  5,  8, 10, 14, 18]),
 array([10, 13, 14, 17, 19, 23, 29]),
 array([17, 18, 24, 26, 29]),
 array([28, 29, 36, 38, 35]),
 array([53, 56, 58, 61, 68, 69, 70, 70]),
 array([ 7, 10, 13, 16, 22, 24, 28]),
 array([68, 70, 73, 80, 81, 84, 89]),
 array([28, 27, 28, 30, 33, 35, 37]),
 array([90, 89, 91, 93, 95, 94]),
 array([ 6,  5,  7,  8, 11, 11]),
 array([33, 32, 34, 35, 39]),
 array([20, 18, 

In [41]:
blah = []
for row in data:
    diff = np.diff(row)
    c1 = np.prod(np.abs(diff)<=3)
    c2 = np.prod(diff<0)
    c3 = np.prod(diff>0)
    answer = c1*(c2+c3)
    print(answer)
    blah.append(answer)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [42]:
np.sum(blah)

526

In [47]:
nerf = (np.abs(tmp)<=3)

In [53]:
nerf.prod(axis=1)

0    1
1    0
2    0
3    1
4    1
5    1
dtype: int64

In [54]:
(tmp<0)

1      2      3      4
0   True   True   True   True
1  False  False  False  False
2   True   True   True   True
3  False   True  False  False
4   True   True  False   True
5  False  False  False  False

In [55]:
(tmp<0).prod(axis=1)

0    1
1    0
2    1
3    0
4    0
5    0
dtype: int64

In [56]:
(tmp>0).prod(axis=1)

0    0
1    1
2    0
3    0
4    0
5    1
dtype: int64

In [58]:
happy = (np.abs(tmp)<=3).prod(axis=1) & ( ((tmp<0).prod(axis=1)) | (tmp>0).prod(axis=1) )

In [59]:
happy.sum()

2